name: Python CI/CD

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Composite Action
        uses: ./.github/workflows/composite_action.yml

      - name: Deploy to Production
        run: echo "Deploying your Flask application here..."

      
