name: Python CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying your Flask application..."

      - name: Run Composite Action
        uses: ./

      
