name: reusable action

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write      
  
jobs:
  reusable_workflow-call:
    if: ${{ github.workflow == 'python-reusable.yml' }}
    uses: solvers-camp/python-reusable-actions/.github/workflows/reusable_workflow.yml@main
    with:
      languages: "['python']"
  
           
      
      
      
      


