name: Python CI/CD

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: echo "Deploying your Flask application here..."

      - name: Run Python CI/CD Composite Action
        uses: ./.github/workflows/action.yml@v2
