name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production
      run: echo "Deploying your Flask application..."
        
    - name: Run Python CI/CD Composite Action
      uses: ./composite_action.yml
