name: Python CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        exclude:
          - os: macos-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.10"
            
    steps:     
      - name: Use reusable actions
        uses: solvers-camp/python-reusable-actions/.github/workflows/reusable_workflow.yml@main
        with:
          languages: "['python']"
           
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production
        shell: bash
        run: echo "Deploy the flask application..."

      
      
      


