name: Python CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "pypy3.9", "pypy3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.9"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying your Flask application..."

      - name: Run Composite Action
        uses: ./

      
