name: Python CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production
        env:
          SECRET_KEY: ${{ secrets.SECRETS_KEY }} 
        shell: bash
        run: echo "Deploy the flask application..."

      - name: Use reusable actions
        uses: solvers-camp/python-reusable-actions/action.yml@main

      
      


