name: reusable action

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  reusable_workflow-call:
    uses: solvers-camp/python-reusable-actions/.github/workflows/reusable_workflow.yml@main

  
           
      
      
      
      


